#ifndef OPENDIGITIZER_TEST_TESTING_BLOCK_INSPECTION_UTILS_HPP
#define OPENDIGITIZER_TEST_TESTING_BLOCK_INSPECTION_UTILS_HPP

#include "GraphSession.hpp"

#include <gnuradio-4.0/BlockModel.hpp>

#include <memory>

namespace opendigitizer::test {

[[nodiscard]] inline std::shared_ptr<gr::BlockModel> findBlockInRootGraph(GraphSession& session, std::string_view name) {
    for (const auto& block : session.graph().blocks()) {
        if (block->name() == name) {
            return block;
        }
    }
    return nullptr;
}

[[nodiscard]] inline gr::pmt::Value setting(GraphSession& session, std::string_view blockName, std::string_view key) {
    const auto block = findBlockInRootGraph(session, blockName);
    return block ? block->settings().get(std::string{key}).value_or(gr::pmt::Value{}) : gr::pmt::Value{};
}

template<typename T>
[[nodiscard]] inline bool blockHasBasicTypeKeyValuePair(GraphSession& session, std::string_view blockName, std::string_view key, T expected) {
    const gr::pmt::Value value = setting(session, blockName, key);
    const T*             typed = value.get_if<T>();
    return typed != nullptr && *typed == expected;
}

[[nodiscard]] inline bool blockHasStringKeyValuePair(GraphSession& session, std::string_view blockName, std::string_view key, std::string_view expected) { //
    const gr::pmt::Value            value = setting(session, blockName, key);
    std::optional<std::string_view> typed = value.get_if<std::string_view>();
    return typed.has_value() && *typed == expected;
}

[[nodiscard]] inline bool blockApproximatelyHasDoubleKeyValuePair(GraphSession& session, std::string_view blockName, std::string_view key, double expected) {
    const gr::pmt::Value value = setting(session, blockName, key);
    const double*        typed = value.get_if<double>();
    return typed != nullptr && std::abs(*typed - expected) < 1e-9;
}

/// The tests usually have some global GraphSession so they can redefine the above functions to automatically use that variable
#define TESTING_BLOCK_INSPECTION_UTILS_MAKE_GLOBAL_STATE_AWARE_OVERLOAD(__function_name, __global_session)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     \
    template<typename First, typename... Args>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 \
    requires(!std::same_as<std::remove_cvref_t<First>, GraphSession>) /* only use this overload if the user isn't already explicitly passing in a GraphSession*/                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               \
    [[nodiscard]] auto __function_name(First&& first, Args&&... args) {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        \
        return opendigitizer::test::__function_name((__global_session), std::forward<First>(first), std::forward<Args>(args)...);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              \
    }

#define TESTING_BLOCK_INSPECTION_UTILS_MAKE_ALL_GLOBAL_STATE_AWARE_OVERLOADS(__global_session)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 \
    TESTING_BLOCK_INSPECTION_UTILS_MAKE_GLOBAL_STATE_AWARE_OVERLOAD(blockHasStringKeyValuePair, (__global_session))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            \
    TESTING_BLOCK_INSPECTION_UTILS_MAKE_GLOBAL_STATE_AWARE_OVERLOAD(blockApproximatelyHasDoubleKeyValuePair, (__global_session))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               \
    TESTING_BLOCK_INSPECTION_UTILS_MAKE_GLOBAL_STATE_AWARE_OVERLOAD(setting, (__global_session))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               \
    template<typename T, typename First, typename... Args>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     \
    requires(!std::same_as<std::remove_cvref_t<First>, GraphSession>)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          \
    [[nodiscard]] auto blockHasBasicTypeKeyValuePair(First&& first, Args&&... args) {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          \
        return opendigitizer::test::blockHasBasicTypeKeyValuePair<T>((__global_session), std::forward<First>(first), std::forward<Args>(args)...);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             \
    }

} // namespace opendigitizer::test

#endif
